# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '012Chat_exit.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Exit(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        self.setupUi()

    def setupUi(self):
        self.setObjectName("Dialog_Exit")
        self.resize(465, 196)
        self.setMinimumSize(QtCore.QSize(465, 196))
        self.setMaximumSize(QtCore.QSize(465, 196))
        self.setStyleSheet("background-color: rgb(255, 255, 255);")
        
        self.btn_ok = QtWidgets.QPushButton(self)
        self.btn_ok.setGeometry(QtCore.QRect(244, 114, 180, 44))
        self.btn_ok.setStyleSheet("background-color: #6F3FE2;\n"
"selection-background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"selection-color: #6F3FE2;\n"
"border: 1px solid #6F3FE2;\n"
"border-radius: 8px;\n"
"font: 10pt \"SEBANG Gothic\";")
        self.btn_ok.setObjectName("btn_ok")
        self.btn_ok.clicked.connect(self.btn_confirm)

        self.btn_no = QtWidgets.QPushButton(self)
        self.btn_no.setGeometry(QtCore.QRect(40, 114, 180, 44))
        self.btn_no.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-background-color: #6F3FE2;\n"
"color: #6F3FE2;\n"
"selection-color: rgb(255, 255, 255);\n"
"border: 1px solid #6F3FE2;\n"
"border-radius: 8px;\n"
"font: 10pt \"SEBANG Gothic\";")
        self.btn_no.setObjectName("btn_no")
        self.btn_no.clicked.connect(self.btn_cancle)

        self.Text_title = QtWidgets.QLabel(self)
        self.Text_title.setGeometry(QtCore.QRect(121, 36, 222, 24))
        self.Text_title.setStyleSheet("font: 75 12pt \"SEBANG Gothic\";\n"
"color: #343A40;")
        self.Text_title.setObjectName("Text_title")
        self.Text_title_2 = QtWidgets.QLabel(self)
        self.Text_title_2.setGeometry(QtCore.QRect(40, 68, 385, 22))
        self.Text_title_2.setStyleSheet("font: 75 10pt \"SEBANG Gothic\";\n"
"color: #ADB5BD;")
        self.Text_title_2.setObjectName("Text_title_2")

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog_Exit", "Exit"))
        self.btn_no.setText(_translate("Dialog_Exit", "No, cancel"))
        self.btn_ok.setText(_translate("Dialog_Exit", "Yes, confirm"))
        self.Text_title.setText(_translate("Dialog_Exit", "<html><head/><body><p align=\"center\">Sure you want to exit?</p></body></html>"))
        self.Text_title_2.setText(_translate("Dialog_Exit", "<html><head/><body><p align=\"center\">Your account will be remove.</p></body></html>"))

    def btn_confirm(self):
        self.accept()
    def btn_cancle(self):
        self.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_Exit = Ui_Dialog_Exit()
    Dialog_Exit.show()
    sys.exit(app.exec_())
