# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/012Chat.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from os import environ
from PyQt5 import QtCore, QtGui, QtWidgets
import dialog_gui1, dialog_exit, widget_emoji
from server import *
from client import *
import sys

#해상도 설정 start
def suppress_qt_warnings():
    environ["QT_DEVICE_PIXEL_RATIO"] = "0"
    environ["QT_AUTO_SCREEN_SCALE_FACTOR"] = "1"
    environ["QT_SCREEN_SCALE_FACTORS"] = "1"
    environ["QT_SCALE_FACTOR"] = "1"

#해상도 설정 end
class Ui_MainWindow(QtWidgets.QMainWindow):
    #__init__ start
    def __init__(self):
        super().__init__()
        self.initUI()
        self.port = 123
        self.nickname = f"Noname{self.port}"
        self.status = None
        self.executeChangeNickname()
        self.emojiWidget = None
    
    def initUI(self):
        self.connect_server()
    
    #서버 연결
    def connect_server(self):
        try:
            HOST = "127.0.0.1"
            PORT = 12346
            connect_to_server(HOST, PORT)
        except Exception as e:
            print('에러 발생:', e)

    #__init__ end
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 832)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 832))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 832))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1280, 832))
        self.centralwidget.setMaximumSize(QtCore.QSize(1280, 832))
        self.centralwidget.setObjectName("centralwidget")
        self.Bg_Sidebar = QtWidgets.QLabel(self.centralwidget)
        self.Bg_Sidebar.setEnabled(True)
        self.Bg_Sidebar.setGeometry(QtCore.QRect(0, 0, 380, 832))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bg_Sidebar.sizePolicy().hasHeightForWidth())
        self.Bg_Sidebar.setSizePolicy(sizePolicy)
        self.Bg_Sidebar.setMinimumSize(QtCore.QSize(380, 832))
        self.Bg_Sidebar.setMaximumSize(QtCore.QSize(380, 832))
        self.Bg_Sidebar.setText("")
        self.Bg_Sidebar.setPixmap(QtGui.QPixmap(":/layout/Sidebar.png"))
        self.Bg_Sidebar.setScaledContents(False)
        self.Bg_Sidebar.setObjectName("Bg_Sidebar")
        self.Bg_Header = QtWidgets.QLabel(self.centralwidget)
        self.Bg_Header.setGeometry(QtCore.QRect(380, 0, 900, 56))
        self.Bg_Header.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Bg_Header.setText("")
        self.Bg_Header.setPixmap(QtGui.QPixmap(":/layout/Header.png"))
        self.Bg_Header.setObjectName("Bg_Header")
        self.Bg_ChatArea = QtWidgets.QLabel(self.centralwidget)
        self.Bg_ChatArea.setGeometry(QtCore.QRect(380, 56, 900, 721))
        self.Bg_ChatArea.setText("")
        self.Bg_ChatArea.setPixmap(QtGui.QPixmap(":/layout/ChatFrame2.png"))
        self.Bg_ChatArea.setObjectName("Bg_ChatArea")
        self.Bg_Input = QtWidgets.QLabel(self.centralwidget)
        self.Bg_Input.setGeometry(QtCore.QRect(380, 777, 900, 56))
        self.Bg_Input.setText("")
        self.Bg_Input.setPixmap(QtGui.QPixmap(":/layout/Footer.png"))
        self.Bg_Input.setObjectName("Bg_Input")
        self.Btn_emoji = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_emoji.setGeometry(QtCore.QRect(424, 793, 24, 24))
        self.Btn_emoji.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(255, 255, 255);\n"
"border-image: url(:/icon/emoji-happy.png);")
        self.Btn_emoji.setText("")
        self.Btn_emoji.setObjectName("Btn_emoji")
        #이모티콘 버튼 함수연결 start
        self.Btn_emoji.clicked.connect(self.openEmoji)
        #이모티콘 버튼 함수연결 end
        self.Input_inputBox = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Input_inputBox.setGeometry(QtCore.QRect(460, 793, 724, 24))
        self.Input_inputBox.setStyleSheet("QPlainTextEdit {\n"
"    border-style: none;\n"
"    font: 12pt \"SEBANG Gothic\";\n"
"    color: #495057;\n"
"}")
        self.Input_inputBox.setLineWidth(1)
        self.Input_inputBox.setPlainText("")
        self.Input_inputBox.setObjectName("Input_inputBox")
        self.Btn_send = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_send.setGeometry(QtCore.QRect(1208, 793, 24, 24))
        self.Btn_send.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(255, 255, 255);\n"
"border-image: url(:/icon/send.png);")
        self.Btn_send.setText("")
        self.Btn_send.setObjectName("Btn_send")
        #전송 버튼 함수연결 start
        self.Btn_send.clicked.connect(self.send)
        #전송 버튼 함수연결 end
        self.Btn_exit = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_exit.setGeometry(QtCore.QRect(44, 793, 24, 24))
        self.Btn_exit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(255, 255, 255);\n"
"border-image: url(:/icon/exit.png)")
        self.Btn_exit.setText("")
        self.Btn_exit.setObjectName("Btn_exit")
        #종료 버튼 함수연결 start
        self.Btn_exit.clicked.connect(self.executeExit)
        #종료 버튼 함수연결 end
        self.Text_ProfileHeader = QtWidgets.QLabel(self.centralwidget)
        self.Text_ProfileHeader.setGeometry(QtCore.QRect(76, 20, 271, 20))
        self.Text_ProfileHeader.setStyleSheet("font: 75 9pt \"SEBANG Gothic\";")
        self.Text_ProfileHeader.setTextFormat(QtCore.Qt.AutoText)
        self.Text_ProfileHeader.setScaledContents(False)
        self.Text_ProfileHeader.setObjectName("Text_ProfileHeader")
        self.Text_MemberHeader = QtWidgets.QLabel(self.centralwidget)
        self.Text_MemberHeader.setGeometry(QtCore.QRect(76, 210, 271, 20))
        self.Text_MemberHeader.setStyleSheet("font: 75 9pt \"SEBANG Gothic\";")
        self.Text_MemberHeader.setMidLineWidth(0)
        self.Text_MemberHeader.setTextFormat(QtCore.Qt.AutoText)
        self.Text_MemberHeader.setScaledContents(False)
        self.Text_MemberHeader.setObjectName("Text_MemberHeader")
        self.Text_Exit = QtWidgets.QLabel(self.centralwidget)
        self.Text_Exit.setGeometry(QtCore.QRect(76, 795, 31, 20))
        self.Text_Exit.setStyleSheet("font: 75 9pt \"SEBANG Gothic\";")
        self.Text_Exit.setMidLineWidth(0)
        self.Text_Exit.setTextFormat(QtCore.Qt.AutoText)
        self.Text_Exit.setScaledContents(False)
        self.Text_Exit.setObjectName("Text_Exit")
        self.Text_ChatFrom = QtWidgets.QLabel(self.centralwidget)
        self.Text_ChatFrom.setGeometry(QtCore.QRect(456, 20, 151, 20))
        self.Text_ChatFrom.setStyleSheet("font: 75 9pt \"SEBANG Gothic\";")
        self.Text_ChatFrom.setTextFormat(QtCore.Qt.AutoText)
        self.Text_ChatFrom.setScaledContents(False)
        self.Text_ChatFrom.setObjectName("Text_ChatFrom")
        self.Img_myProfile = QtWidgets.QLabel(self.centralwidget)
        self.Img_myProfile.setGeometry(QtCore.QRect(44, 92, 48, 48))
        self.Img_myProfile.setText("")
        self.Img_myProfile.setPixmap(QtGui.QPixmap(":/image/profile-circle.png"))
        self.Img_myProfile.setObjectName("Img_myProfile")
        self.Text_myName = QtWidgets.QLabel(self.centralwidget)
        self.Text_myName.setGeometry(QtCore.QRect(108, 100, 161, 20))
        self.Text_myName.setStyleSheet("font: 75 12pt \"SEBANG Gothic\";")
        self.Text_myName.setObjectName("Text_myName")
        self.Text_myStatus = QtWidgets.QLabel(self.centralwidget)
        self.Text_myStatus.setGeometry(QtCore.QRect(126, 122, 161, 20))
        self.Text_myStatus.setStyleSheet("font: 75 12pt \"SEBANG Gothic\";")
        self.Text_myStatus.setObjectName("Text_myStatus")
        self.Img_MyStatus = QtWidgets.QLabel(self.centralwidget)
        self.Img_MyStatus.setGeometry(QtCore.QRect(108, 125, 12, 12))
        self.Img_MyStatus.setText("")
        self.Img_MyStatus.setPixmap(QtGui.QPixmap(":/icon/OnlineDot.png"))
        self.Img_MyStatus.setObjectName("Img_MyStatus")
        self.Btn_edit = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_edit.setGeometry(QtCore.QRect(320, 100, 20, 20))
        self.Btn_edit.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.Btn_edit.setStyleSheet("background-color: #F4F0FD;\n"
"selection-background-color: #F4F0FD;\n"
"border-image: url(:/icon/edit.png)")
        self.Btn_edit.setText("")
        self.Btn_edit.setObjectName("Btn_edit")
        #닉네임 편집버튼 함수연결 start
        self.Btn_edit.clicked.connect(self.executeChangeNickname)
        #닉네임 편집버튼 함수연결 end
        self.memberTable = QtWidgets.QTableWidget(self.centralwidget)
        self.memberTable.setGeometry(QtCore.QRect(44, 262, 311, 498))
        self.memberTable.setStyleSheet("* {\n"
"    font: 9pt \"SEBANG Gothic\";\n"
"}\n"
"QTableWidget {\n"
"    border-style: none;\n"
"}\n"
"QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar:vertical {\n"
"    border-style: none;\n"
"    background:white;\n"
"    width:10px;    \n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"QScrollBar::handle:vertical {         \n"
"    min-height: 0px;\n"
"    border-style: none;\n"
"    border-radius: 5px;\n"
"    background-color: #6F3FE2;\n"
"}\n"
"QScrollBar::add-line:vertical {       \n"
"    height: 0px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0 px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"")
        self.memberTable.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.memberTable.setShowGrid(False)
        self.memberTable.setRowCount(24)
        self.memberTable.setObjectName("memberTable")
        self.memberTable.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.memberTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.memberTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.memberTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.memberTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.memberTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.memberTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.memberTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.memberTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("세방고딕 Regular")
        font.setPointSize(9)
        item.setFont(font)
        self.memberTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("SEBANG Gothic")
        item.setFont(font)
        self.memberTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        font = QtGui.QFont()
        font.setFamily("SEBANG Gothic")
        item.setFont(font)
        self.memberTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.memberTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.memberTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.memberTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.memberTable.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.memberTable.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.memberTable.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.memberTable.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.memberTable.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.memberTable.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.memberTable.setItem(9, 0, item)
        self.memberTable.horizontalHeader().setDefaultSectionSize(140)
        self.memberTable.horizontalHeader().setSortIndicatorShown(False)
        self.memberTable.horizontalHeader().setStretchLastSection(True)
        self.memberTable.verticalHeader().setVisible(False)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(390, 56, 890, 688))
        self.scrollArea.setMinimumSize(QtCore.QSize(890, 688))
        self.scrollArea.setMaximumSize(QtCore.QSize(890, 688))
        self.scrollArea.setStyleSheet("border-style: none;\n"
"background-color: #F1F8F9;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 870, 920))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(870, 688))
        self.scrollAreaWidgetContents.setMaximumSize(QtCore.QSize(870, 16777215))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(0, -1, 0, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.chat_frame5 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.chat_frame5.setMinimumSize(QtCore.QSize(830, 0))
        self.chat_frame5.setMaximumSize(QtCore.QSize(880, 16777215))
        self.chat_frame5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chat_frame5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chat_frame5.setObjectName("chat_frame5")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.chat_frame5)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.name5 = QtWidgets.QLabel(self.chat_frame5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name5.sizePolicy().hasHeightForWidth())
        self.name5.setSizePolicy(sizePolicy)
        self.name5.setMinimumSize(QtCore.QSize(830, 16))
        self.name5.setMaximumSize(QtCore.QSize(880, 16))
        self.name5.setStyleSheet("color: #343A40;\n"
"font: 700 10pt \"SEBANG Gothic\";")
        self.name5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.name5.setObjectName("name5")
        self.verticalLayout_15.addWidget(self.name5)
        self.content5 = QtWidgets.QLabel(self.chat_frame5)
        self.content5.setMinimumSize(QtCore.QSize(830, 16))
        self.content5.setMaximumSize(QtCore.QSize(880, 16777215))
        self.content5.setStyleSheet("color: #343A40;\n"
"font: 10pt \"SEBANG Gothic\";")
        self.content5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.content5.setWordWrap(True)
        self.content5.setObjectName("content5")
        self.verticalLayout_15.addWidget(self.content5)
        self.gridLayout.addWidget(self.chat_frame5, 4, 0, 1, 1)
        self.chat_frame1 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.chat_frame1.setMinimumSize(QtCore.QSize(830, 0))
        self.chat_frame1.setMaximumSize(QtCore.QSize(880, 16777215))
        self.chat_frame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chat_frame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chat_frame1.setObjectName("chat_frame1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.chat_frame1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.name1 = QtWidgets.QLabel(self.chat_frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name1.sizePolicy().hasHeightForWidth())
        self.name1.setSizePolicy(sizePolicy)
        self.name1.setMinimumSize(QtCore.QSize(830, 16))
        self.name1.setMaximumSize(QtCore.QSize(880, 16))
        self.name1.setStyleSheet("color: #343A40;\n"
"font: 700 10pt \"SEBANG Gothic\";")
        self.name1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.name1.setObjectName("name1")
        self.verticalLayout_2.addWidget(self.name1)
        self.content1 = QtWidgets.QLabel(self.chat_frame1)
        self.content1.setMinimumSize(QtCore.QSize(830, 16))
        self.content1.setMaximumSize(QtCore.QSize(880, 16777215))
        self.content1.setStyleSheet("color: #343A40;\n"
"font: 10pt \"SEBANG Gothic\";")
        self.content1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.content1.setWordWrap(True)
        self.content1.setObjectName("content1")
        self.verticalLayout_2.addWidget(self.content1)
        self.gridLayout.addWidget(self.chat_frame1, 0, 0, 1, 1)
        self.chat_frame3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.chat_frame3.setMinimumSize(QtCore.QSize(830, 0))
        self.chat_frame3.setMaximumSize(QtCore.QSize(880, 16777215))
        self.chat_frame3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chat_frame3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chat_frame3.setObjectName("chat_frame3")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.chat_frame3)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.name3 = QtWidgets.QLabel(self.chat_frame3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name3.sizePolicy().hasHeightForWidth())
        self.name3.setSizePolicy(sizePolicy)
        self.name3.setMinimumSize(QtCore.QSize(830, 16))
        self.name3.setMaximumSize(QtCore.QSize(880, 16))
        self.name3.setStyleSheet("color: #343A40;\n"
"font: 700 10pt \"SEBANG Gothic\";")
        self.name3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.name3.setObjectName("name3")
        self.verticalLayout_13.addWidget(self.name3)
        self.content3 = QtWidgets.QLabel(self.chat_frame3)
        self.content3.setMinimumSize(QtCore.QSize(830, 16))
        self.content3.setMaximumSize(QtCore.QSize(880, 16777215))
        self.content3.setStyleSheet("color: #343A40;\n"
"font: 10pt \"SEBANG Gothic\";")
        self.content3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.content3.setWordWrap(True)
        self.content3.setObjectName("content3")
        self.verticalLayout_13.addWidget(self.content3)
        self.gridLayout.addWidget(self.chat_frame3, 2, 0, 1, 1)
        self.chat_frame6 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.chat_frame6.setMinimumSize(QtCore.QSize(830, 0))
        self.chat_frame6.setMaximumSize(QtCore.QSize(880, 16777215))
        self.chat_frame6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chat_frame6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chat_frame6.setObjectName("chat_frame6")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.chat_frame6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.name6 = QtWidgets.QLabel(self.chat_frame6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name6.sizePolicy().hasHeightForWidth())
        self.name6.setSizePolicy(sizePolicy)
        self.name6.setMinimumSize(QtCore.QSize(830, 16))
        self.name6.setMaximumSize(QtCore.QSize(880, 16))
        self.name6.setStyleSheet("color: #343A40;\n"
"font: 700 10pt \"SEBANG Gothic\";")
        self.name6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.name6.setObjectName("name6")
        self.verticalLayout.addWidget(self.name6)
        self.content6 = QtWidgets.QLabel(self.chat_frame6)
        self.content6.setMinimumSize(QtCore.QSize(830, 16))
        self.content6.setMaximumSize(QtCore.QSize(880, 16777215))
        self.content6.setStyleSheet("color: #343A40;\n"
"font: 10pt \"SEBANG Gothic\";")
        self.content6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.content6.setWordWrap(True)
        self.content6.setObjectName("content6")
        self.verticalLayout.addWidget(self.content6)
        self.gridLayout.addWidget(self.chat_frame6, 5, 0, 1, 1)
        self.chat_frame2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.chat_frame2.setMinimumSize(QtCore.QSize(830, 0))
        self.chat_frame2.setMaximumSize(QtCore.QSize(880, 16777215))
        self.chat_frame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chat_frame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chat_frame2.setObjectName("chat_frame2")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.chat_frame2)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.name2 = QtWidgets.QLabel(self.chat_frame2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name2.sizePolicy().hasHeightForWidth())
        self.name2.setSizePolicy(sizePolicy)
        self.name2.setMinimumSize(QtCore.QSize(830, 16))
        self.name2.setMaximumSize(QtCore.QSize(880, 16))
        self.name2.setStyleSheet("color: #343A40;\n"
"font: 700 10pt \"SEBANG Gothic\";")
        self.name2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.name2.setObjectName("name2")
        self.verticalLayout_14.addWidget(self.name2)
        self.content2 = QtWidgets.QLabel(self.chat_frame2)
        self.content2.setMinimumSize(QtCore.QSize(830, 16))
        self.content2.setMaximumSize(QtCore.QSize(880, 16777215))
        self.content2.setStyleSheet("color: #343A40;\n"
"font: 10pt \"SEBANG Gothic\";")
        self.content2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.content2.setWordWrap(True)
        self.content2.setObjectName("content2")
        self.verticalLayout_14.addWidget(self.content2)
        self.gridLayout.addWidget(self.chat_frame2, 1, 0, 1, 1)
        self.chat_frame4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.chat_frame4.setMinimumSize(QtCore.QSize(830, 0))
        self.chat_frame4.setMaximumSize(QtCore.QSize(880, 16777215))
        self.chat_frame4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chat_frame4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chat_frame4.setObjectName("chat_frame4")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.chat_frame4)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.name4 = QtWidgets.QLabel(self.chat_frame4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name4.sizePolicy().hasHeightForWidth())
        self.name4.setSizePolicy(sizePolicy)
        self.name4.setMinimumSize(QtCore.QSize(830, 16))
        self.name4.setMaximumSize(QtCore.QSize(880, 16))
        self.name4.setStyleSheet("color: #343A40;\n"
"font: 700 10pt \"SEBANG Gothic\";")
        self.name4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.name4.setObjectName("name4")
        self.verticalLayout_16.addWidget(self.name4)
        self.content4 = QtWidgets.QLabel(self.chat_frame4)
        self.content4.setMinimumSize(QtCore.QSize(830, 16))
        self.content4.setMaximumSize(QtCore.QSize(880, 16777215))
        self.content4.setStyleSheet("color: #343A40;\n"
"font: 10pt \"SEBANG Gothic\";")
        self.content4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.content4.setWordWrap(True)
        self.content4.setObjectName("content4")
        self.verticalLayout_16.addWidget(self.content4)
        self.gridLayout.addWidget(self.chat_frame4, 3, 0, 1, 1)
        self.gridLayout.setRowStretch(5, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.Frame_typingNotice = QtWidgets.QFrame(self.centralwidget)
        self.Frame_typingNotice.setGeometry(QtCore.QRect(380, 743, 900, 32))
        self.Frame_typingNotice.setMinimumSize(QtCore.QSize(900, 32))
        self.Frame_typingNotice.setMaximumSize(QtCore.QSize(900, 32))
        self.Frame_typingNotice.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame_typingNotice.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame_typingNotice.setObjectName("Frame_typingNotice")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Frame_typingNotice)
        self.horizontalLayout.setContentsMargins(4, 4, 16, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Gif_typingIndicator = QtWidgets.QLabel(self.Frame_typingNotice)
        self.Gif_typingIndicator.setMinimumSize(QtCore.QSize(28, 28))
        self.Gif_typingIndicator.setMaximumSize(QtCore.QSize(28, 28))
        self.Gif_typingIndicator.setText("")
        self.Gif_typingIndicator.setObjectName("Gif_typingIndicator")
        self.horizontalLayout.addWidget(self.Gif_typingIndicator)
        self.movie_typingIndicator = QtGui.QMovie("typing_indicator.gif")
        self.Gif_typingIndicator.setMovie(self.movie_typingIndicator)
        self.movie_typingIndicator.start()
        spacerItem = QtWidgets.QSpacerItem(8, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.Frame_typingNotice)
        self.label_2.setStyleSheet("color: #343A40;\n"
"font: 9pt \"SEBANG Gothic\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.Bg_Input.raise_()
        self.Bg_Sidebar.raise_()
        self.Bg_Header.raise_()
        self.Bg_ChatArea.raise_()
        self.Btn_emoji.raise_()
        self.Input_inputBox.raise_()
        self.Btn_send.raise_()
        self.Btn_exit.raise_()
        self.Text_ProfileHeader.raise_()
        self.Text_MemberHeader.raise_()
        self.Text_Exit.raise_()
        self.Text_ChatFrom.raise_()
        self.Img_myProfile.raise_()
        self.Text_myName.raise_()
        self.Text_myStatus.raise_()
        self.Img_MyStatus.raise_()
        self.Btn_edit.raise_()
        self.memberTable.raise_()
        self.scrollArea.raise_()
        self.Frame_typingNotice.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Input_inputBox.setPlaceholderText(_translate("MainWindow", "Text here..."))
        self.Text_ProfileHeader.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Profile</span></p></body></html>"))
        self.Text_MemberHeader.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Members</span></p></body></html>"))
        self.Text_Exit.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Exit</span></p></body></html>"))
        self.Text_ChatFrom.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Chat : ALL</span></p></body></html>"))
        #초기 닉네임 설정 start
        self.Text_myName.setText(_translate("MainWindow", f"<html><head/><body><p>{self.nickname}</p></body></html>"))
        #초기 닉네임 설정 end
        self.Text_myStatus.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">ONLINE</span></p></body></html>"))
        item = self.memberTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.memberTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.memberTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.memberTable.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.memberTable.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.memberTable.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.memberTable.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.memberTable.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.memberTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.memberTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Status"))
        __sortingEnabled = self.memberTable.isSortingEnabled()
        self.memberTable.setSortingEnabled(False)
        item = self.memberTable.item(0, 0)
        item.setText(_translate("MainWindow", "Noname"))
        item = self.memberTable.item(0, 1)
        item.setText(_translate("MainWindow", "Online"))
        item = self.memberTable.item(1, 0)
        item.setText(_translate("MainWindow", "Noname001"))
        item = self.memberTable.item(2, 0)
        item.setText(_translate("MainWindow", "Noname002"))
        item = self.memberTable.item(3, 0)
        item.setText(_translate("MainWindow", "Noname005"))
        self.memberTable.setSortingEnabled(__sortingEnabled)
        
        self.name5.setText(_translate("MainWindow", "Welcome 012 Chat!"))
        self.label_2.setText(_translate("MainWindow", "입력중인 사용자: Noname1, Noname3, Noname4"))

    #서버로 부터 이모티콘 이름 받으면 content5에 출력
    #def show_emogi(self, filename):

    #서버로 부터 받은 메시지 contetn5에 출력 (아직 안됨..)
    def print_data(self):
        server_data = decoded_data
        self.content5.setText(server_data)

    #메시지 서버로 보내기(엔터 치면 보내지는 것도 구현해야 함 - 아직은 버튼 클릭으로만 보내짐)
    def send(self):
        message = self.Input_inputBox.toPlainText()
        if message:    
            send_message(message)  
            self.Input_inputBox.clear()  #메시지 보낸 후 입력창 비우기

    def executeChangeNickname(self):
        changeDialog = dialog_gui1.Ui_Dialog()
        if changeDialog.exec_():
            self.nickname = changeDialog.Input_text.text()
            try:
                self.Text_myName.setText(self.nickname)
            except:
                return

    def executeExit(self):
        exitDialog = dialog_exit.Ui_Dialog_Exit()
        if exitDialog.exec_():
            QtWidgets.QApplication.quit()

    def openEmoji(self):
        if self.emojiWidget is None:
            self.emojiWidget = widget_emoji.Ui_Form()
        self.emojiWidget.show()

    #메인 윈도우가 닫힐 때 서버 연결 종료
    def close(self, event):
        event.accept()
        close_connection() 

import resource_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())